CREATE DATABASE UMG;
USE DATABASE UMG;
CREATE TABLE SEDES
(
CODIGOSEDE VARCHAR(5) PRIMARY KEY,
NOMBRESEDE VARCHAR(50) NOT NULL,
NOMBRECOORDINADORSEDE VARCHAR(50) NOT NULL,
DIRECCIONSEDE VARCHAR(30) NOT NULL,
TELEFONOSEDE VARCHAR(20) NOT NULL
) ENGINE = INNODB;
