CREATE DATABASE UMG;
USE UMG;
CREATE TABLE PUESTOS
(
CODIGOPUESTO VARCHAR(5) PRIMARY KEY,
NOMBREPUESTO VARCHAR(50) NOT NULL,
ESTATUSPUESTO VARCHAR(1) NOT NULL
) ENGINE=INNODB;
CREATE TABLE DEPARTAMENTOS
(
CODIGODEPARTAMENTO VARCHAR (5) PRIMARY KEY,
NOMBREDEPARTAMENTO VARCHAR (50) NOT NULL,
ESTATUSDEPARTAMENTO VARCHAR (1) NOT NULL
) ENGINE=INNODB;
CREATE TABLE EMPLEADOS 
(
CODIGOEMPLEADO VARCHAR (5) PRIMARY KEY,
NOMBREEMPLEADO VARCHAR (50) NOT NULL,
CUIEMPLEADO VARCHAR (20) NOT NULL,
CODIGODEPARTAMENTO VARCHAR (5) NOT NULL,
CODIGOPUESTO VARCHAR (5) NOT NULL,
ESTATUSEMPLEADO VARCHAR (1) NOT NULL,
FOREIGN KEY (CODIGOPUESTO) REFERENCES PUESTOS (CODIGOPUESTO),
FOREIGN KEY (CODIGODEPARTAMENTO) REFERENCES DEPARTAMENTOS (CODIGODEPARTAMENTO)
)ENGINE=INNODB;
