CREATE DATABASE UMG;
USE UMG;
CREATE TABLE ADMINISTRACION
(
CodigoAdministracion VARCHAR(5)Primary Key,
NombreAdministrador VARCHAR(50)NOT NULL ,
Asignaciones VARCHAR(1)NOT NULL,
SALARIOS VARCHAR(2)NOT NULL,
SEDEPERSONAL VARCHAR(2)NOT NULL
) ENGINE = INNODB;
