CREATE DATABASE UNIVERSIDAD;
USE UNIVERSIDAD;
CREATE TABLE ALUMNOS  
(
CODIGODEALUMNO VARCHAR (5) PRIMARY KEY,
NOMBREDEALUMNNO VARCHAR (50) NOT NULL,
ESTATUSDEALUMNO VARCHAR (1) NOT NULL,
CARRERAASIGNADA VARCHAR (2) NOT NULL,
SEMESTREASIGNADO VARCHAR (2) NOT NULL

) ENGINE=INNODB;

CREATE TABLE CARRERAS
(
CODIGODECARRERA VARCHAR (5) PRIMARY KEY,
NOMBREDECARRERA VARCHAR (50) NOT NULL,
ESTUDIANTESASIGNADOS VARCHAR (1) NOT NULL,
CODIGODECURSOS VARCHAR (1) NOT NULL

) ENGINE=INNODB;


